<x-app-layout>
    <x-slot name="header"><div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p class="placard mb-1.5 text-[0.6rem]">Administrare / Jurnal rulări</p><h2 class="font-sans text-xl font-bold text-[#eaf4f6] sm:text-2xl">Detalii rulare</h2></div><a href="{{ route('admin.crawl-logs') }}" class="beamkey focus-ring rounded-sm px-4 py-2.5 text-[0.65rem]">&larr; Jurnal rulări</a></div></x-slot>
    <div class="py-8 sm:py-10"><div class="mx-auto max-w-7xl space-y-8 px-4 sm:px-6 lg:px-8">
        <section class="border border-hairline graticule" aria-labelledby="trace-heading"><div class="flex flex-wrap items-end justify-between gap-4 border-b border-hairline px-5 py-4"><div><p class="placard text-[0.6rem]">Trasă de execuție</p><h3 id="trace-heading" class="mt-1 font-sans text-lg font-bold text-[#eaf4f6]">Rulare #{{ $crawlLog->id }}</h3></div><x-admin.partials.status :status="$crawlLog->status" :total-errors="$crawlLog->total_errors" /></div><dl class="grid divide-x divide-y divide-hairline md:grid-cols-2"><div class="p-5"><dt class="placard text-[0.55rem]">Tip</dt><dd class="mt-2 font-sans text-[#eaf4f6]">{{ ucfirst(str_replace('_', ' ', $crawlLog->type)) }}</dd></div><div class="p-5"><dt class="placard text-[0.55rem]">Declanșată de</dt><dd class="mt-2 text-[#eaf4f6]">{{ ucfirst($crawlLog->triggered_by) }} @if($crawlLog->user)({{ $crawlLog->user->name }})@endif</dd></div><div class="p-5"><dt class="placard text-[0.55rem]">Pornită</dt><dd class="mt-2 font-mono text-[0.75rem] tabular-nums text-[#eaf4f6]">{{ $crawlLog->started_at->format('d M Y, H:i:s') }}</dd></div><div class="p-5"><dt class="placard text-[0.55rem]">Finalizată / durată</dt><dd class="mt-2 font-mono text-[0.75rem] tabular-nums text-[#eaf4f6]">{{ $crawlLog->completed_at ? $crawlLog->completed_at->format('d M Y, H:i:s') : 'nefinalizată' }} · {{ $crawlLog->formatted_duration }}</dd></div>@if($crawlLog->notes)<div class="p-5 md:col-span-2"><dt class="placard text-[0.55rem]">Notițe</dt><dd class="mt-2 text-sm text-dim">{{ $crawlLog->notes }}</dd></div>@endif</dl></section>
        <section aria-label="Statistici rulare" class="border-y border-hairline"><div class="grid grid-cols-2 divide-x divide-y divide-hairline lg:grid-cols-4 lg:divide-y-0"><div class="p-5"><p class="placard text-[0.55rem]">Căutări procesate</p><p class="mt-2 font-mono text-2xl font-bold tabular-nums text-[#eaf4f6]">{{ $crawlLog->hunted_deals_processed }}</p>@if($crawlLog->hunted_deals_failed > 0)<p class="mt-1 font-mono text-[0.65rem] text-em-red">{{ $crawlLog->hunted_deals_failed }} eșuate</p>@endif</div><div class="p-5"><p class="placard text-[0.55rem]">Anunțuri găsite</p><p class="mt-2 font-mono text-2xl font-bold tabular-nums text-[#eaf4f6]">{{ number_format($crawlLog->total_listings_found) }}</p>@if($crawlLog->listings_per_second)<p class="mt-1 font-mono text-[0.65rem] text-dim">{{ $crawlLog->listings_per_second }}/s</p>@endif</div><div class="p-5"><p class="placard text-[0.55rem]">Anunțuri noi</p><p class="mt-2 font-mono text-2xl font-bold tabular-nums text-[#eaf4f6]">{{ number_format($crawlLog->new_deals_created) }}</p>@if($crawlLog->deals_updated > 0)<p class="mt-1 font-mono text-[0.65rem] text-dim">{{ number_format($crawlLog->deals_updated) }} actualizate</p>@endif</div><div class="p-5"><p class="placard text-[0.55rem]">Instantanee create</p><p class="mt-2 font-mono text-2xl font-bold tabular-nums text-[#eaf4f6]">{{ number_format($crawlLog->snapshots_created) }}</p>@if($crawlLog->success_rate !== null)<p class="mt-1 font-mono text-[0.65rem] text-em-green">{{ $crawlLog->success_rate }}% reușită</p>@endif</div></div></section>
        @if($crawlLog->configuration)<section class="border border-hairline bg-bench" aria-labelledby="config-heading"><div class="border-b border-hairline px-5 py-4"><p class="placard text-[0.6rem]">Sursă execuție</p><h3 id="config-heading" class="mt-1 font-sans text-lg font-bold text-[#eaf4f6]">Configurația rulării</h3></div><dl class="divide-y divide-hairline">@foreach($crawlLog->configuration as $key => $value)<div class="grid gap-2 px-5 py-4 sm:grid-cols-[minmax(0,1fr)_minmax(14rem,1fr)]"><dt class="font-sans text-sm font-semibold text-[#eaf4f6]">{{ ucfirst(str_replace('_', ' ', $key)) }}</dt><dd class="break-all font-mono text-[0.7rem] text-dim">@if(is_bool($value)){{ $value ? 'Activată' : 'Dezactivată' }}@elseif(is_array($value)){{ json_encode($value) }}@else{{ $value ?: 'Nestabilită' }}@endif</dd></div>@endforeach</dl></section>@endif
        @if($crawlLog->total_errors > 0 && $crawlLog->errors)<section class="border border-[#ff5d5d]/50" aria-labelledby="errors-heading"><div class="border-b border-[#ff5d5d]/50 px-5 py-4"><p class="placard text-[0.6rem] text-em-red">Erori factuale</p><h3 id="errors-heading" class="mt-1 font-sans text-lg font-bold text-[#eaf4f6]">Erori ({{ $crawlLog->total_errors }})</h3></div><ol class="divide-y divide-hairline">@foreach($crawlLog->errors as $index => $error)<li class="grid gap-3 px-5 py-4 sm:grid-cols-[4rem_minmax(0,1fr)]"><span class="font-mono text-[0.65rem] text-em-red">#{{ $index + 1 }}</span><p class="break-words text-sm text-dim">{{ $error }}</p></li>@endforeach</ol></section>@endif
        @if($crawlLog->duration_ms && $crawlLog->total_listings_found > 0)
            <section class="border border-hairline" aria-labelledby="performance-heading">
                <div class="border-b border-hairline bg-bench px-5 py-4">
                    <p class="placard text-[0.6rem]">Măsurători</p>
                    <h3 id="performance-heading" class="mt-1 font-sans text-lg font-bold text-[#eaf4f6]">Performanța execuției</h3>
                </div>
                <dl class="grid divide-x divide-y divide-hairline sm:grid-cols-3 sm:divide-y-0">
                    <div class="p-5"><dt class="placard text-[0.55rem]">Durată totală</dt><dd class="mt-2 font-mono text-lg tabular-nums text-[#eaf4f6]">{{ $crawlLog->formatted_duration }}</dd></div>
                    @if($crawlLog->listings_per_second)
                        <div class="p-5"><dt class="placard text-[0.55rem]">Anunțuri pe secundă</dt><dd class="mt-2 font-mono text-lg tabular-nums text-[#eaf4f6]">{{ $crawlLog->listings_per_second }}</dd></div>
                    @endif
                    @if($crawlLog->hunted_deals_processed > 0)
                        <div class="p-5"><dt class="placard text-[0.55rem]">Timp mediu / căutare</dt><dd class="mt-2 font-mono text-lg tabular-nums text-[#eaf4f6]">{{ round($crawlLog->duration_ms / $crawlLog->hunted_deals_processed) }} ms</dd></div>
                    @endif
                </dl>
            </section>
        @endif
    </div></div>
</x-app-layout>
