<x-app-layout>
    <x-slot name="header">
        <div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
            <div><p class="placard mb-1.5 text-[0.6rem]">Administrare</p><h2 class="font-sans text-xl font-bold text-[#eaf4f6] sm:text-2xl">Panou de control</h2></div>
            <div class="flex flex-wrap gap-2.5"><a href="{{ route('admin.system-health') }}" class="beamkey focus-ring rounded-sm px-4 py-2.5 text-[0.65rem]">Stare sistem</a><a href="{{ route('admin.crawl-logs') }}" class="beamkey beamkey-armed focus-ring rounded-sm px-4 py-2.5 text-[0.65rem]">Jurnal rulări</a></div>
        </div>
    </x-slot>

    <div class="py-8 sm:py-10"><div class="mx-auto max-w-7xl space-y-8 px-4 sm:px-6 lg:px-8">
        <section class="border border-hairline graticule" aria-labelledby="alignment-heading">
            <div class="flex flex-col gap-5 border-b border-hairline px-5 py-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="placard text-[0.6rem]">Aliniere curentă</p><h3 id="alignment-heading" class="mt-1 font-sans text-lg font-bold text-[#eaf4f6]">Stare sistem</h3></div><div class="flex items-center gap-4"><p class="font-mono text-[0.65rem] tabular-nums text-dim/70">ultima citire {{ $systemHealth['last_check'] ? $systemHealth['last_check']->diffForHumans() : 'niciodată' }}</p><form action="{{ route('admin.run-health-check') }}" method="POST">@csrf <button class="beamkey focus-ring rounded-sm px-4 py-2.5 text-[0.65rem]">Rulează verificarea</button></form></div></div>
            <div class="divide-y divide-hairline">@forelse($systemHealth['components'] as $component => $health)<div class="grid gap-3 px-5 py-4 sm:grid-cols-[minmax(0,1fr)_10rem_8rem] sm:items-center"><div><p class="font-sans font-semibold capitalize text-[#eaf4f6]">{{ str_replace('_', ' ', $component) }}</p>@if($health)<p class="mt-1 text-sm text-dim">{{ $health->message }}</p>@endif</div>@if($health)<x-admin.partials.status :status="$health->status" />@else<x-admin.partials.status status="pending" />@endif<p class="font-mono text-[0.7rem] tabular-nums text-dim sm:text-right">{{ $health?->response_time_ms ? $health->response_time_ms.' ms' : 'fără timp' }}</p></div>@empty<p class="px-5 py-8 text-sm text-dim">Nu există componente de afișat.</p>@endforelse</div>
        </section>

        <section aria-label="Citiri în ultimele 24 de ore" class="border-y border-hairline"><div class="grid grid-cols-2 divide-x divide-y divide-hairline lg:grid-cols-4 lg:divide-y-0"><div class="p-5"><p class="placard text-[0.55rem]">Rulări, 24 h</p><p class="mt-2 font-mono text-2xl font-bold tabular-nums text-[#eaf4f6]">{{ $crawlStats['total_crawls'] }}</p><p class="mt-1 text-sm text-em-green">{{ $crawlStats['successful_crawls'] }} reușite</p></div><div class="p-5"><p class="placard text-[0.55rem]">Anunțuri citite</p><p class="mt-2 font-mono text-2xl font-bold tabular-nums text-[#eaf4f6]">{{ number_format($crawlStats['total_listings_found']) }}</p><p class="mt-1 text-sm text-beam">{{ number_format($crawlStats['total_deals_created']) }} noi</p></div><div class="p-5"><p class="placard text-[0.55rem]">Căutări active</p><p class="mt-2 font-mono text-2xl font-bold tabular-nums text-[#eaf4f6]">{{ $activeHuntedDeals }}</p><p class="mt-1 text-sm text-dim">{{ number_format($totalDeals) }} anunțuri total</p></div><div class="p-5"><p class="placard text-[0.55rem]">Rată reușită</p><p class="mt-2 font-mono text-2xl font-bold tabular-nums text-[#eaf4f6]">{{ number_format($crawlStats['average_success_rate'] ?? 0, 1) }}%</p><p class="mt-1 text-sm text-dim">ultimele 24 de ore</p></div></div></section>

        <section class="border border-hairline bg-bench" aria-labelledby="manual-heading"><div class="border-b border-hairline px-5 py-4"><p class="placard text-[0.6rem]">Execuție</p><h3 id="manual-heading" class="mt-1 font-sans text-lg font-bold text-[#eaf4f6]">Pornește o rulare manuală</h3></div><form action="{{ route('admin.trigger-crawl') }}" method="POST" class="px-5 py-5">@csrf <div class="grid gap-4 md:grid-cols-3"><div><label for="hunted_deal_id" class="placard text-[0.6rem]">Căutare urmărită</label><select name="hunted_deal_id" id="hunted_deal_id" class="mt-2 block w-full rounded-none border-hairline bg-[#06080a] text-sm text-[#eaf4f6] focus:border-[#59e3ff]/60 focus:ring-[#59e3ff]/30"><option value="">Toate căutările active</option>@foreach(\App\Models\HuntedDeal::where('is_active', true)->with('user')->get() as $huntedDeal)<option value="{{ $huntedDeal->id }}">{{ $huntedDeal->search_term }} ({{ $huntedDeal->user->name ?? 'necunoscut' }})</option>@endforeach</select></div><div><label for="notes" class="placard text-[0.6rem]">Notițe</label><input type="text" name="notes" id="notes" placeholder="Motivul rulării manuale" class="mt-2 block w-full rounded-none border-hairline bg-[#06080a] text-sm text-[#eaf4f6] placeholder:text-dim/50 focus:border-[#59e3ff]/60 focus:ring-[#59e3ff]/30"></div><label class="flex items-end gap-2 pb-2 font-mono text-[0.7rem] text-dim"><input type="checkbox" name="dry_run" value="1" class="rounded-none border-hairline bg-[#06080a] text-[#59e3ff] focus:ring-[#59e3ff]/40"> Simulare</label></div><div class="mt-5 flex justify-end"><button class="beamkey beamkey-armed focus-ring rounded-sm px-4 py-2.5 text-[0.65rem]">Pornește rularea</button></div></form></section>

        <section aria-labelledby="recent-heading"><div class="mb-4 flex items-end justify-between gap-3"><div><p class="placard text-[0.6rem]">Trasă de execuție</p><h3 id="recent-heading" class="mt-1 font-sans text-lg font-bold text-[#eaf4f6]">Rulări recente</h3></div><a href="{{ route('admin.crawl-logs') }}" class="rail-link focus-ring rounded-sm border-b pb-0.5 text-[0.65rem]">Jurnal complet &rarr;</a></div><div class="border-t border-hairline">@forelse($recentCrawls as $crawl)<article class="grid gap-3 border-b border-hairline py-4 sm:grid-cols-[10rem_minmax(0,1fr)_9rem] sm:items-center"><p class="font-mono text-[0.7rem] tabular-nums text-dim">{{ $crawl->started_at->format('d M Y, H:i') }}</p><div><div class="flex flex-wrap items-center gap-x-3 gap-y-1"><p class="font-sans font-semibold text-[#eaf4f6]">{{ ucfirst(str_replace('_', ' ', $crawl->type)) }}</p><x-admin.partials.status :status="$crawl->status" :total-errors="$crawl->total_errors" /></div><p class="mt-1 font-mono text-[0.65rem] tabular-nums text-dim/70">{{ $crawl->total_listings_found }} găsite · {{ $crawl->new_deals_created }} noi · {{ ucfirst($crawl->triggered_by) }}@if($crawl->user) ({{ $crawl->user->name }})@endif</p></div><a href="{{ route('admin.crawl-logs.show', $crawl) }}" class="rail-link focus-ring rounded-sm border-b pb-0.5 text-[0.65rem] sm:justify-self-end">Detalii</a></article>@empty<p class="border-b border-hairline px-5 py-8 text-sm text-dim">Nu există rulări recente.</p>@endforelse</div></section>

        <section class="border border-hairline bg-bench" aria-labelledby="config-heading"><div class="flex items-end justify-between gap-3 border-b border-hairline px-5 py-4"><div><p class="placard text-[0.6rem]">Citire configurație</p><h3 id="config-heading" class="mt-1 font-sans text-lg font-bold text-[#eaf4f6]">Parametri activi</h3></div><a href="{{ route('admin.configuration') }}" class="rail-link focus-ring rounded-sm border-b pb-0.5 text-[0.65rem]">Vezi configurația &rarr;</a></div><dl class="grid divide-x divide-y divide-hairline sm:grid-cols-2"><div class="p-5"><dt class="placard text-[0.55rem]">Pagină maximă / căutare</dt><dd class="mt-2 font-mono tabular-nums text-[#eaf4f6]">{{ $crawlerConfig['max_pages_per_search'] }}</dd></div><div class="p-5"><dt class="placard text-[0.55rem]">Întârziere cerere</dt><dd class="mt-2 font-mono tabular-nums text-[#eaf4f6]">{{ $crawlerConfig['request_delay_ms'] }} ms</dd></div><div class="p-5"><dt class="placard text-[0.55rem]">Anunțuri maxime / rulare</dt><dd class="mt-2 font-mono tabular-nums text-[#eaf4f6]">{{ $crawlerConfig['max_listings_per_run'] }}</dd></div><div class="p-5"><dt class="placard text-[0.55rem]">Clasificare AI</dt><dd class="mt-2 font-mono text-[0.75rem] {{ $crawlerConfig['ai_classification_enabled'] ? 'text-em-green' : 'text-em-red' }}">{{ $crawlerConfig['ai_classification_enabled'] ? 'Activată' : 'Dezactivată' }}</dd></div></dl></section>
    </div></div>
</x-app-layout>
